Repository pysal/pointpats, pull requests merged in 2023-09, with the labels that each got.

#105 Fix support truncation and remove superfluous content
  notebooks/distance_statistics.ipynb
  pointpats/_deprecated_distance_statistics.py
  pointpats/distance_statistics.py
  pointpats/ripley.py
  pointpats/tests/test_distance_statistics.py
  pointpats/tests/test_ripley.py
Labels: rough edge

#117 migrate to pyproject
  .coveragerc
  .github/release.yml
  .github/workflows/build_docs.yml
  .github/workflows/release_and_publish.yml
  CHANGELOG.txt
  MANIFEST.in
  codecov.yml
  environment.yml
  pyproject.toml
  readthedocs.yml
  requirements.txt
  requirements_tests.txt
  setup.py
  tools/gitcount.ipynb
Labels: maintenance

#124 CI: update actions
  .github/workflows/build_docs.yml
  .github/workflows/tests.yaml
Labels: testing

#127 readme in pyproject
  pyproject.toml
Labels: docs

#128 update codecov badge
  .github/release.yml
  README.md
Labels: maintenance

#129 add density plot to api docs
  docs/api.rst
Labels: maintenance
